import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import '../../../data/models/character.dart';
import '../../../data/providers/character_provider.dart';
import '../../../data/repositories/character_repository.dart';
import '../../../data/providers/auth_provider.dart';
import '../../../core/constants/app_constants.dart';

class CharacterCreateScreen extends ConsumerStatefulWidget {
  final String? characterId;

  const CharacterCreateScreen({super.key, this.characterId});

  @override
  ConsumerState<CharacterCreateScreen> createState() => _CharacterCreateScreenState();
}

class _CharacterCreateScreenState extends ConsumerState<CharacterCreateScreen> {
  final _formKey = GlobalKey<FormState>();
  final _nameController = TextEditingController();
  final _personalityController = TextEditingController();
  final _speechStyleController = TextEditingController();
  final _backstoryController = TextEditingController();
  final _scenarioController = TextEditingController();
  final _firstMessageController = TextEditingController();
  final _exampleDialogueController = TextEditingController();
  final _tagController = TextEditingController();

  final List<String> _tags = [];
  String? _avatarUrl;
  bool _isGeneratingAvatar = false;
  String? _characterId; // For avatar generation after save
  bool _isEditMode = false;

  @override
  void initState() {
    super.initState();
    if (widget.characterId != null) {
      _isEditMode = true;
      _characterId = widget.characterId;
      _loadCharacter();
    }
  }

  Future<void> _loadCharacter() async {
    try {
      final apiClient = ref.read(apiClientProvider);
      final repository = CharacterRepository(apiClient);
      final character = await repository.getCharacter(widget.characterId!);
      setState(() {
        _nameController.text = character.name;
        _personalityController.text = character.personality;
        _speechStyleController.text = character.speechStyle;
        _backstoryController.text = character.backstory;
        _scenarioController.text = character.scenario;
        _firstMessageController.text = character.firstMessage;
        _exampleDialogueController.text = character.exampleDialogue;
        _tags.addAll(character.tags);
        _avatarUrl = character.avatarUrl;
      });
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('로딩 실패: $e')));
      }
    }
  }

  @override
  void dispose() {
    _nameController.dispose();
    _personalityController.dispose();
    _speechStyleController.dispose();
    _backstoryController.dispose();
    _scenarioController.dispose();
    _firstMessageController.dispose();
    _exampleDialogueController.dispose();
    _tagController.dispose();
    super.dispose();
  }

  Future<void> _showAutoGenerateDialog() async {
    final sourceWorkController = TextEditingController();
    final characterNameController = TextEditingController();

    final result = await showDialog<Map<String, String>>(
      context: context,
      builder: (context) => AlertDialog(
        title: const Text('원작에서 가져오기'),
        content: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            TextField(
              controller: sourceWorkController,
              decoration: const InputDecoration(
                labelText: '작품명 *',
                hintText: '예: 죠죠의 기묘한 모험',
              ),
            ),
            const SizedBox(height: 16),
            TextField(
              controller: characterNameController,
              decoration: const InputDecoration(
                labelText: '캐릭터 이름 *',
                hintText: '예: 디오',
              ),
            ),
          ],
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(context),
            child: const Text('취소'),
          ),
          TextButton(
            onPressed: () {
              if (sourceWorkController.text.isNotEmpty &&
                  characterNameController.text.isNotEmpty) {
                Navigator.pop(context, {
                  'source_work': sourceWorkController.text,
                  'character_name': characterNameController.text,
                });
              }
            },
            child: const Text('생성'),
          ),
        ],
      ),
    );

    if (result != null) {
      await _autoGenerateCharacter(
        sourceWork: result['source_work']!,
        characterName: result['character_name']!,
      );
    }
  }

  Future<void> _autoGenerateCharacter({
    required String sourceWork,
    required String characterName,
  }) async {
    try {
      // Show loading
      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('캐릭터 생성 중...')),
      );

      final apiClient = ref.read(apiClientProvider);
      final repository = CharacterRepository(apiClient);

      final generated = await repository.autoGenerateCharacter(
        sourceWork: sourceWork,
        characterName: characterName,
      );

      // Fill form fields
      setState(() {
        _nameController.text = generated.name;
        _personalityController.text = generated.personality;
        _speechStyleController.text = generated.speechStyle;
        _backstoryController.text = generated.backstory;
        _scenarioController.text = generated.scenario;
        _firstMessageController.text = generated.firstMessage;
        _exampleDialogueController.text = generated.exampleDialogue;
        _tags.clear();
        if (generated.tags.isNotEmpty) {
          _tags.addAll(generated.tags);
        }
      });

      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('캐릭터가 자동 생성되었습니다. 확인 후 저장하세요.')),
      );
    } catch (e) {
      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('자동 생성 실패: $e')),
      );
    }
  }

  Future<void> _generateAvatar() async {
    if (_characterId == null) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('먼저 캐릭터를 저장하세요')),
      );
      return;
    }

    setState(() {
      _isGeneratingAvatar = true;
    });

    try {
      final apiClient = ref.read(apiClientProvider);
      final repository = CharacterRepository(apiClient);

      final avatarUrl = await repository.generateAvatar(_characterId!);

      setState(() {
        _avatarUrl = avatarUrl;
        _isGeneratingAvatar = false;
      });

      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('아바타가 생성되었습니다')),
      );
    } catch (e) {
      setState(() {
        _isGeneratingAvatar = false;
      });

      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('아바타 생성 실패: $e')),
      );
    }
  }

  Future<void> _saveCharacter() async {
    if (!_formKey.currentState!.validate()) {
      return;
    }

    final character = CharacterCreate(
      name: _nameController.text,
      personality: _personalityController.text,
      speechStyle: _speechStyleController.text,
      backstory: _backstoryController.text,
      scenario: _scenarioController.text,
      firstMessage: _firstMessageController.text,
      exampleDialogue: _exampleDialogueController.text,
      tags: _tags,
      avatarUrl: _avatarUrl,
    );

    if (_isEditMode) {
      // Update existing character
      try {
        final apiClient = ref.read(apiClientProvider);
        await apiClient.put(
          '/api/v1/characters/$_characterId',
          data: character.toJson(),
        );
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(content: Text('캐릭터가 수정되었습니다')),
          );
          ref.invalidate(characterListProvider);
          context.pop();
        }
      } catch (e) {
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(content: Text('수정 실패: $e')),
          );
        }
      }
      return;
    }

    await ref.read(characterCreateProvider.notifier).createCharacter(character);

    if (mounted) {
      final state = ref.read(characterCreateProvider);
      state.when(
        data: (createdCharacter) {
          if (createdCharacter != null) {
            // Store character ID for avatar generation
            _characterId = createdCharacter.id;

            ScaffoldMessenger.of(context).showSnackBar(
              const SnackBar(content: Text('캐릭터가 생성되었습니다')),
            );
            ref.invalidate(characterListProvider);
            context.pop();
          }
        },
        loading: () {},
        error: (error, stack) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(content: Text('오류: $error')),
          );
        },
      );
    }
  }

  void _addTag() {
    final tag = _tagController.text.trim();
    if (tag.isNotEmpty && !_tags.contains(tag)) {
      setState(() {
        _tags.add(tag);
        _tagController.clear();
      });
    }
  }

  void _removeTag(String tag) {
    setState(() {
      _tags.remove(tag);
    });
  }

  @override
  Widget build(BuildContext context) {
    final createState = ref.watch(characterCreateProvider);

    return Scaffold(
      appBar: AppBar(
        title: Text(_isEditMode ? '캐릭터 편집' : '새 캐릭터'),
        actions: [
          TextButton(
            onPressed: createState.isLoading ? null : _saveCharacter,
            child: const Text('저장'),
          ),
        ],
      ),
      body: Form(
        key: _formKey,
        child: ListView(
          padding: const EdgeInsets.all(16),
          children: [
            // Auto-generate button
            OutlinedButton.icon(
              onPressed: _showAutoGenerateDialog,
              icon: const Icon(Icons.auto_awesome),
              label: const Text('원작에서 가져오기'),
              style: OutlinedButton.styleFrom(
                padding: const EdgeInsets.symmetric(vertical: 12),
              ),
            ),
            const SizedBox(height: 24),

            // Avatar section
            Center(
              child: Column(
                children: [
                  CircleAvatar(
                    radius: 50,
                    backgroundImage: AppConstants.resolveAvatarUrl(_avatarUrl) != null
                        ? NetworkImage(AppConstants.resolveAvatarUrl(_avatarUrl)!)
                        : null,
                    child: AppConstants.resolveAvatarUrl(_avatarUrl) == null
                        ? const Icon(Icons.person, size: 50)
                        : null,
                  ),
                  const SizedBox(height: 8),
                  const SizedBox(height: 8),
                  TextButton.icon(
                    onPressed: () async {
                      final controller = TextEditingController(text: _avatarUrl ?? '');
                      final url = await showDialog<String>(
                        context: context,
                        builder: (ctx) => AlertDialog(
                          title: const Text('이미지 URL'),
                          content: TextField(
                            controller: controller,
                            decoration: const InputDecoration(
                              hintText: 'https://... 이미지 주소 붙여넣기',
                            ),
                            autofocus: true,
                          ),
                          actions: [
                            TextButton(onPressed: () => Navigator.pop(ctx), child: const Text('취소')),
                            if (_avatarUrl != null)
                              TextButton(
                                onPressed: () => Navigator.pop(ctx, ''),
                                child: const Text('삭제', style: TextStyle(color: Colors.red)),
                              ),
                            FilledButton(
                              onPressed: () => Navigator.pop(ctx, controller.text),
                              child: const Text('확인'),
                            ),
                          ],
                        ),
                      );
                      if (url != null) {
                        setState(() {
                          _avatarUrl = url.isEmpty ? null : url;
                        });
                      }
                    },
                    icon: const Icon(Icons.image),
                    label: Text(_avatarUrl != null ? '이미지 변경' : '이미지 URL 설정'),
                  ),
                ],
              ),
            ),
            const SizedBox(height: 24),

            TextFormField(
              controller: _nameController,
              decoration: const InputDecoration(
                labelText: '이름 *',
                hintText: '캐릭터 이름',
              ),
              validator: (value) {
                if (value == null || value.isEmpty) {
                  return '이름을 입력하세요';
                }
                return null;
              },
            ),
            const SizedBox(height: 16),
            TextFormField(
              controller: _personalityController,
              decoration: const InputDecoration(
                labelText: '성격 *',
                hintText: '상냥하고 호기심 많음',
              ),
              maxLines: 3,
              validator: (value) {
                if (value == null || value.isEmpty) {
                  return '성격을 입력하세요';
                }
                return null;
              },
            ),
            const SizedBox(height: 16),
            TextFormField(
              controller: _speechStyleController,
              decoration: const InputDecoration(
                labelText: '말투 *',
                hintText: '따뜻하고 부드러움',
              ),
              maxLines: 2,
              validator: (value) {
                if (value == null || value.isEmpty) {
                  return '말투를 입력하세요';
                }
                return null;
              },
            ),
            const SizedBox(height: 16),
            TextFormField(
              controller: _backstoryController,
              decoration: const InputDecoration(
                labelText: '배경 스토리 *',
                hintText: '캐릭터의 과거와 설정',
              ),
              maxLines: 5,
              validator: (value) {
                if (value == null || value.isEmpty) {
                  return '배경 스토리를 입력하세요';
                }
                return null;
              },
            ),
            const SizedBox(height: 16),
            TextFormField(
              controller: _scenarioController,
              decoration: const InputDecoration(
                labelText: '시나리오 (선택)',
                hintText: '대화 상황 설정',
              ),
              maxLines: 3,
            ),
            const SizedBox(height: 16),
            TextFormField(
              controller: _firstMessageController,
              decoration: const InputDecoration(
                labelText: '첫 메시지 (선택)',
                hintText: '캐릭터의 첫 인사',
              ),
              maxLines: 3,
            ),
            const SizedBox(height: 16),
            TextFormField(
              controller: _exampleDialogueController,
              decoration: const InputDecoration(
                labelText: '예시 대화 (선택)',
                hintText: '<START>\n유저: 안녕?\n캐릭터: 안녕하세요!',
              ),
              maxLines: 5,
            ),
            const SizedBox(height: 16),
            const Text(
              '태그',
              style: TextStyle(fontSize: 16, fontWeight: FontWeight.w600),
            ),
            const SizedBox(height: 8),
            Row(
              children: [
                Expanded(
                  child: TextField(
                    controller: _tagController,
                    decoration: const InputDecoration(
                      hintText: '태그 입력',
                    ),
                    onSubmitted: (_) => _addTag(),
                  ),
                ),
                const SizedBox(width: 8),
                IconButton(
                  icon: const Icon(Icons.add),
                  onPressed: _addTag,
                ),
              ],
            ),
            const SizedBox(height: 8),
            if (_tags.isNotEmpty)
              Wrap(
                spacing: 8,
                children: _tags.map((tag) {
                  return Chip(
                    label: Text(tag),
                    onDeleted: () => _removeTag(tag),
                  );
                }).toList(),
              ),
            const SizedBox(height: 32),
            if (createState.isLoading)
              const Center(child: CircularProgressIndicator()),
          ],
        ),
      ),
    );
  }
}
