"""Add group chat support: is_group, character_id in messages, group_conversation_participants

Revision ID: 80e52326d13f
Revises: 86841f61fcd1
Create Date: 2026-03-20 11:38:47.979868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.db.types import GUID


# revision identifiers, used by Alembic.
revision: str = '80e52326d13f'
down_revision: Union[str, Sequence[str], None] = '86841f61fcd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_conversation_participants',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('conversation_id', GUID(length=36), nullable=False),
    sa.Column('character_id', GUID(length=36), nullable=False),
    sa.Column('turn_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'character_id', name='uq_conversation_character')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_group', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.alter_column('character_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('character_id', GUID(length=36), nullable=True))
        batch_op.create_foreign_key('fk_messages_character_id', 'characters', ['character_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint('fk_messages_character_id', type_='foreignkey')
        batch_op.drop_column('character_id')

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.alter_column('character_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
        batch_op.drop_column('is_group')

    op.drop_table('group_conversation_participants')
    # ### end Alembic commands ###
