"""add_scenario_characters_knowledge_private_state

Revision ID: 86841f61fcd1
Revises: 94f3d9a053a1
Create Date: 2026-03-20 11:15:23.625630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.db.types import GUID


# revision identifiers, used by Alembic.
revision: str = '86841f61fcd1'
down_revision: Union[str, Sequence[str], None] = '94f3d9a053a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_knowledge',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('character_id', GUID(length=36), nullable=False),
    sa.Column('scenario_id', GUID(length=36), nullable=False),
    sa.Column('known_facts', sa.JSON(), nullable=False),
    sa.Column('unknown_facts', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id', 'scenario_id', name='uq_character_scenario_knowledge')
    )
    op.create_table('character_private_state',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('character_id', GUID(length=36), nullable=False),
    sa.Column('scenario_id', GUID(length=36), nullable=False),
    sa.Column('inner_thoughts', sa.Text(), nullable=False),
    sa.Column('feelings_toward', sa.JSON(), nullable=False),
    sa.Column('secrets', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id', 'scenario_id', name='uq_character_scenario_state')
    )
    op.create_table('scenario_characters',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('scenario_id', GUID(length=36), nullable=False),
    sa.Column('character_id', GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scenario_id', 'character_id', name='uq_scenario_character')
    )
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=GUID(length=36),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.NUMERIC(),
               type_=GUID(length=36),
               existing_nullable=False)

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=GUID(length=36),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.NUMERIC(),
               type_=GUID(length=36),
               existing_nullable=False)
        batch_op.alter_column('character_id',
               existing_type=sa.NUMERIC(),
               type_=GUID(length=36),
               existing_nullable=False)
        batch_op.alter_column('scenario_id',
               existing_type=sa.NUMERIC(),
               type_=GUID(length=36),
               existing_nullable=True)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=GUID(length=36),
               existing_nullable=False)
        batch_op.alter_column('conversation_id',
               existing_type=sa.NUMERIC(),
               type_=GUID(length=36),
               existing_nullable=False)

    with op.batch_alter_table('scenarios', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=GUID(length=36),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.NUMERIC(),
               type_=GUID(length=36),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=GUID(length=36),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=GUID(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('scenarios', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=GUID(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=GUID(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('conversation_id',
               existing_type=GUID(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=GUID(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.alter_column('scenario_id',
               existing_type=GUID(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('character_id',
               existing_type=GUID(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=GUID(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=GUID(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=GUID(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=GUID(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    op.drop_table('scenario_characters')
    op.drop_table('character_private_state')
    op.drop_table('character_knowledge')
    # ### end Alembic commands ###
